server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices
  application:
    name: hotel-service
  config:
    import: optional:configserver:http://localhost:8084

okta:
  oauth2:
    issuer: https://dev-26630661.okta.com/oauth2/default
    audience: api://default
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
